// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1596106566);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1596106686);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1594265387);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1596106446);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1596106806);
user_pref("browser.cache.disk.amount_written", 0);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.search.region", "KE");
user_pref("datareporting.sessions.current.activeTicks", 4);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 2821);
user_pref("datareporting.sessions.current.main", 101);
user_pref("datareporting.sessions.current.startTime", "1594265356390");
user_pref("datareporting.sessions.current.totalTime", 119);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Mon, 20 Jul 2020 15:21:58 GMT");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{\"langpack-en-GB@thunderbird.mozilla.org\":{\"version\":\"52.7.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/thunderbird/extensions/langpack-en-GB@thunderbird.mozilla.org.xpi\",\"runInSafeMode\":false,\"dependencies\":[],\"hasEmbeddedWebExtension\":false}}");
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.e10s.rollout.hasAddon", false);
user_pref("extensions.e10sBlockedByAddons", true);
user_pref("extensions.enabledAddons", "messagingmenu%40mozilla.com:1.3.1,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:52.7.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1596106569);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200629235513");
user_pref("extensions.lastAppVersion", "68.10.0");
user_pref("extensions.lastPlatformVersion", "68.10.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"01509e1d-5b07-4637-ad41-e67c54cd22dc\",\"default-theme@mozilla.org\":\"065229d1-9c85-486f-9772-d927e07310a6\",\"google@search.mozilla.org\":\"c7ca45b6-e1a0-45ae-b3fd-3c1e1a55ac05\",\"amazondotcom@search.mozilla.org\":\"b200d0a4-01b9-4aa2-b10a-1943ab08dd42\",\"bing@search.mozilla.org\":\"55e59026-c881-4d49-bbd4-759952bee663\",\"ddg@search.mozilla.org\":\"ea153838-c1c3-4571-85ea-9b39056a2707\",\"twitter@search.mozilla.org\":\"5cfbb597-7e92-49bb-b3e0-02b73108180d\",\"wikipedia@search.mozilla.org\":\"52e3e3ab-8d4b-48eb-9d1c-09a93ce7c6f0\"}");
user_pref("extensions.xpiState", "{\"app-global\":{\"messagingmenu@mozilla.com\":{\"d\":\"/usr/lib/thunderbird/extensions/messagingmenu@mozilla.com.xpi\",\"e\":true,\"v\":\"1.3.1\",\"st\":1523890993000},\"langpack-en-GB@thunderbird.mozilla.org\":{\"d\":\"/usr/lib/thunderbird/extensions/langpack-en-GB@thunderbird.mozilla.org.xpi\",\"e\":true,\"v\":\"52.7.0\",\"st\":1523890993000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/thunderbird/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"52.7.0\",\"st\":1523890993000}}}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.attachment.store.version", 1);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 17);
user_pref("mailnews.database.global.datastore.id", "3ad044c9-bc81-449a-ae53-01b485d65ff");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "68.10.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("security.sandbox.plugin.tempDirSuffix", "cf45a65f-9be1-4b46-866d-faddf6e4a625");
user_pref("services.blocklist.pinning.checked", 1596107571);
user_pref("services.settings.clock_skew_seconds", -1125);
user_pref("services.settings.last_etag", "\"1596067279709\"");
user_pref("services.settings.last_update_seconds", 1596107571);
user_pref("services.settings.main.hijack-blocklists.last_check", 1596107571);
user_pref("services.settings.main.language-dictionaries.last_check", 1596107571);
user_pref("services.settings.main.sites-classification.last_check", 1596107571);
user_pref("services.settings.security.onecrl.checked", 1596107571);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.telemetry.cachedClientID", "117862e0-5330-4f4c-ab02-3b6ff60f5a24");
user_pref("toolkit.telemetry.previousBuildID", "20180416164209");
user_pref("toolkit.telemetry.prompted", 2);
